Repository devfile/registry-support, pull requests merged in 2022-09, with the labels that each got.

#133 proxy support for registry
  registry-library/library/library.go
  registry-library/library/util.go
Labels: lgtm, approved

#132 Track telemetry download events for GET requests only
  index/server/pkg/server/index.go
Labels: lgtm, approved

#135 Apply DCO to registry-support
  CONTRIBUTING.md
  DCO
  README.md
Labels: lgtm

#137 Add code coverage reporting
  .codecov.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yaml
  .github/workflows/codecov.yaml
  index/server/cover.out
Labels: approved

#136 custom timeout support for registry
  registry-library/README.md
  registry-library/library/library.go
  registry-library/library/library_test.go
  registry-library/library/util.go
Labels: lgtm, approved

#139 backport proxy support. Includes fixes for both devfile/api#926 and …
  registry-library/README.md
  registry-library/library/library.go
  registry-library/library/library_test.go
Labels: lgtm, approved

#141 backport proxy changes to console 4.9
  registry-library/README.md
  registry-library/library/library.go
  registry-library/library/library_test.go
Labels: lgtm, approved

#140 License updates
  .github/workflows/ci.yaml
  add_licenses.sh
  check_licenses.sh
  index/generator/library/library.go
  index/generator/library/library_test.go
  index/generator/library/util.go
  index/generator/library/util_test.go
  index/generator/schema/schema.go
  index/server/docs/docs.go
  index/server/main.go
  index/server/pkg/ocitest/ocitest.go
  index/server/pkg/server/constants.go
  index/server/pkg/server/endpoint.go
  index/server/pkg/server/endpoint_test.go
  index/server/pkg/server/index.go
  index/server/pkg/server/registry.go
  index/server/pkg/util/filter.go
  index/server/pkg/util/filter_test.go
  index/server/pkg/util/telemetry.go
  index/server/pkg/util/telemetry_test.go
  index/server/pkg/util/util.go
  index/server/pkg/util/util_test.go
  license_header.txt
  registry-library/library/library_test.go
  registry-library/library/util_test.go
  tests/integration/pkg/tests/constants.go
  tests/integration/pkg/util/cmd_wrapper.go
  tests/integration/pkg/util/helper_run.go
  tests/integration/pkg/util/util.go
Labels: lgtm, approved
